export const skills = [
  "semantic and accessible HTML",
  "Git",
  "Responsive Web Design",
  "React 19",
  "Github pull requests and reviews",
  "Javascript: ES6+",
  "CSS: Sass",
  "CSS: Flexbox",
  "CSS: Grid",
  "CSS: BEM",
  "CSS: inline styles",
  "NPM",
  "Working with APIs",
  "Markdown",
  "Bootstrap",
  "React Router",
  "Trello",
  "TypeScript",
  "React Hooks",
  "CSS Modules",
  "Tailwind CSS",
  "Vite",
];

export const skillsNext = ["Next.js", "Node.js"];
